
imt:
  minimum_separation_distance_bs_ue: 35
  interfered_with: false
  frequency: 7300.0
  bandwidth: 100
  rb_bandwidth: 0.18
  adjacent_antenna_model: SINGLE_ELEMENT
  spectral_mask: IMT-2020
  spurious_emissions: -13
  guard_band_ratio: 0.1
  channel_model: UMa
  shadowing: true
  topology:
    type: MACROCELL
    macrocell:
      intersite_distance: 600
      wrap_around: false
      num_clusters: 1
  bs:
    load_probability: 0.5
    conducted_power: 22
    height: 18
    noise_figure: 6
    ohmic_loss: 0
  
  ue:
    k: 3
    k_m: 1
    indoor_percent: 70.0
    distribution_type: UNIFORM_IN_CELL
    distribution_distance: RAYLEIGH
    distribution_azimuth: NORMAL
    tx_power_control: true
    p_o_pusch: -92.2
    alpha: 0.8
    p_cmax: 23
    power_dynamic_range: 56
    height: 1.5
    noise_figure: 13
    ohmic_loss: 0
    body_loss: 4
    
  downlink:
    attenuation_factor: 0.6
    sinr_min: -10
    sinr_max: 30
  uplink:
    attenuation_factor: 0.4
    sinr_min: -10
    sinr_max: 22
  imt_dl_intra_sinr_calculation_disabled: true
single_earth_station:
  frequency: 7300
  bandwidth: 1
  tx_power_density: 0
  noise_temperature: 300
  adjacent_ch_selectivity: 20.0
  polarization_loss: 0
  geometry:
    height: 1
    azimuth:
      type: FIXED
      fixed: 180
    elevation:
      type: FIXED
      fixed: 30
    location:
      type: FIXED
      fixed:
        x: 0
        y: 11600
  antenna:
    pattern: OMNI
    gain: 4
  channel_model: P452
  param_p452:
    atmospheric_pressure: 1017
    air_temperature: 293.15
    N0: 352.58
    delta_N: 60
    percentage_p: 0.2
    Dct: 101
    Dcr: 100
    Hte: 6
    Hre: 1
    tx_lat: -15.79
    rx_lat: -15.85
    polarization: horizontal
    clutter_loss: true
    clutter_type: both_ends
general:
  seed: 83
  num_snapshots: 100
  overwrite_output: false
  output_dir: campaigns/campaign_test/output/
  output_dir_prefix: output_campaign_test
  system: SINGLE_EARTH_STATION
  imt_link: DOWNLINK
  enable_adjacent_channel: false
  enable_cochannel: true