import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  aboutSidebar: [
    {
       type: 'autogenerated',
      dirName: '.',
    }
    ],
  downloadSidebar: [
    {
       type: 'autogenerated', 
       dirName: '.' 
      }
    ],
  troubleshootingSidebar: [
    { 
      type: 'autogenerated', 
      dirName: '.' 
    }
  ],

};

export default sidebars;
